### ISSUE TITLE
[Bug]: TypeError: format is not a function

### ISSUE THREAD

**Issue by poovarasanvasudevan** [cloudscape-design/components#1225]
### Browser

Chrome, Safari, Firefox, Edge

### Package version

3.0.312

### React version

18.2.0

### Description

TypeError: format is not a function

```
 FAIL  src/__test__/ActionItem.test.tsx (16.712 s)
  ● Action Items › On Action Items Render

    TypeError: format is not a function

      100 |
      101 |         // ACT
    > 102 |         render(<ActionItems/>);
          |               ^
      103 |
      104 |         // ASSERT
      105 |         expect(screen.getByRole('heading', {name: /Action Items/i})).toBeInTheDocument();

      at i18n (node_modules/@cloudscape-design/components/i18n/lib/default/i18n/context.ts:64:12)
      at Component (node_modules/@cloudscape-design/components/pagination/lib/default/pagination/internal.tsx:93:25)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:16305:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:20074:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21587:16)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)


```

### Source code

ActionItem:
```

import React, {useContext, useEffect, useState} from "react";
import {Box, Button, ButtonDropdown, SpaceBetween, TableProps, TextFilter} from "@cloudscape-design/components";
import {CommonItem} from "../../types/CommonItem";
import {
    ActionItemResultTable,
    createPagination,
    pageSizePreference,
    TableState
} from "../../components/table/ApplicationResultTable";
import {useCollection} from "@cloudscape-design/collection-hooks";
import CollectionPreferences from "@cloudscape-design/components/collection-preferences";
import Table from "@cloudscape-design/components/table";
import Header from "@cloudscape-design/components/header";


const ActionItems = () => {
    const [actionItems, setActionItems] = useState<CommonItem[]>([])
    const [selectedItems, setSelectedItems] = useState<CommonItem[]>([])
    const [isLoading, setLoading] = useState<boolean>(false)
    const [isActionVisible, setActionVisible] = useState<boolean>(false)

    const loadActionItems = async () => {
    }

    const onSelectItems = (item: CommonItem[]) => {
        item.find((item) => item.Status === 'processing') ? setActionVisible(false) : setActionVisible(true)
        setSelectedItems(item)
    }

    const columnDefinitions: Array<TableProps.ColumnDefinition<CommonItem>> = [
        {
            header: "Request Time",
            cell: ({RequestTimeStamp}) => RequestTimeStamp,
            sortingField: 'RequestTimeStamp',
            minWidth: 200,
        },
    ];
    const updateOperation = async (type: string) => {
      
    }

    useEffect(() => {
        loadActionItems().catch((error) => {
            console.log(error)
        })
    }, [])


    const [tableState, setTableState] = useState<TableState>({
        header: "G Items",
        start: 1,
        itemsPerPage: 20
    });

    const {
        items,
        filterProps,
        collectionProps
    } = useCollection(actionItems, {
        filtering: {
            empty: (
                <Box textAlign='center' color='inherit'>
                    <b>No resources</b>
                    <Box padding={{bottom: 's'}} variant='p' color='inherit'>
                        No resources to display.
                    </Box>
                </Box>
            ),
            noMatch: (
                <Box textAlign='center' color='inherit'>
                    <b>No match</b>
                    <Box padding={{bottom: 's'}} variant='p' color='inherit'>
                        No resources matched.
                    </Box>
                </Box>
            ),
        },
    });

    const pagination = createPagination(tableState, setTableState, items);
    const preferences = <CollectionPreferences
        title="Preferences"
        pageSizePreference={pageSizePreference}
        preferences={{
            pageSize: tableState.itemsPerPage
        }}
        wrapLinesPreference={{}}
        stripedRowsPreference={{}}
        contentDensityPreference={{}}
        onConfirm={(e) => {
            setTableState({
                ...tableState,
                itemsPerPage: e.detail.pageSize || 20
            });
        }}
        confirmLabel="Confirm"
        cancelLabel="Cancel"
    />;

    return <Table
        {...collectionProps}
        header={<Header variant={"awsui-h1-sticky"} actions={<></>}
                        counter={`(${items.length})`}>{tableState.header}</Header>}
        variant={"full-page"}
        loading={isLoading}
        onSelectionChange={(e) => {
            onSelectItems(e.detail.selectedItems);
        }}
        selectedItems={selectedItems}
        loadingText={'Loading resources'}
        stickyHeader={true}
        selectionType={"single"}
        resizableColumns={true}
        filter={
            <TextFilter {...filterProps} filteringPlaceholder="Find resources"/>
        }
        preferences={
            preferences
        }
        pagination={pagination}
        columnDefinitions={columnDefinitions}
        items={items.slice(
            (tableState.start - 1) * tableState.itemsPerPage,
            tableState.start * tableState.itemsPerPage
        )}
        wrapLines={true}
    ></Table>
}

export default ActionItems
```

Test:
```
 it("On Action Items Render", async () => {
        // @ts-ignore
        useContext.mockReturnValue(getUserContext([]));
        // ARRANGE
        mockServerToReturnItems([
            actionItem1,
            actionItem2
        ]);


        // ACT
        render(<ActionItems/>);

        // ASSERT
        expect(screen.getByRole('heading', {name: /Action Items/i})).toBeInTheDocument();
    });

```

i had this issue in other test case as well

```
  ● Action Items › Action Items with admin group › should render the action button

    TypeError: format is not a function

      154 |             ]);
      155 |
    > 156 |             render(
          |                   ^
      157 |                 <ActionItems/>
      158 |             )
      159 |         });

      at i18n (node_modules/@cloudscape-design/components/i18n/lib/default/i18n/context.ts:64:12)
      at Component (node_modules/@cloudscape-design/components/collection-preferences/lib/default/collection-preferences/index.tsx:111:20)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:16305:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:20074:13)


```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by poovarasanvasudevan** [comment]
but works in `@cloudscape-design/components`  < 3.0.312

**Comment by just-boris** [comment]
Even if it worked, it was an unsupported configuration. We cannot promise compatibility for unsupported stuff. You need to revisit your testing approach
