### ISSUE TITLE
[Bug]: SyntaxError: \8 and \9 are not allowed in strict mode

### ISSUE THREAD

**Issue by greenpau** [cloudscape-design/components#2180]
### Browser

Chrome

### Package version

3.0.615

### React version

v18.2.0

### Description

Running `jest` results in `SyntaxError: \8 and \9 are not allowed in strict mode` error.

```
> app@1.0.0 test
> jest

  console.error
    Error: Uncaught [SyntaxError: \8 and \9 are not allowed in strict mode.]
        at reportException (omitted/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at innerInvokeEventListeners (omitted/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
        at invokeEventListeners (omitted/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
        at HTMLUnknownElementImpl._dispatch (omitted/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
        at HTMLUnknownElementImpl.dispatchEvent (omitted/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
        at HTMLUnknownElement.dispatchEvent (omitted/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
        at Object.invokeGuardedCallbackDev (omitted/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
        at invokeGuardedCallback (omitted/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
        at reportUncaughtErrorInDEV (omitted/node_modules/react-dom/cjs/react-dom.development.js:22838:5)
        at captureCommitPhaseError (omitted/node_modules/react-dom/cjs/react-dom.development.js:27126:5)
        at commitLayoutMountEffects_complete (omitted/node_modules/react-dom/cjs/react-dom.development.js:24690:9)
        at commitLayoutEffects_begin (omitted/node_modules/react-dom/cjs/react-dom.development.js:24674:7)
        at commitLayoutEffects (omitted/node_modules/react-dom/cjs/react-dom.development.js:24612:3)
        at commitRootImpl (omitted/node_modules/react-dom/cjs/react-dom.development.js:26823:5)
        at commitRoot (omitted/node_modules/react-dom/cjs/react-dom.development.js:26682:5)
        at performSyncWorkOnRoot (omitted/node_modules/react-dom/cjs/react-dom.development.js:26117:3)
        at flushSyncCallbacks (omitted/node_modules/react-dom/cjs/react-dom.development.js:12042:22)
        at commitRootImpl (omitted/node_modules/react-dom/cjs/react-dom.development.js:26959:3)
        at commitRoot (omitted/node_modules/react-dom/cjs/react-dom.development.js:26682:5)
        at finishConcurrentRender (omitted/node_modules/react-dom/cjs/react-dom.development.js:25981:9)
        at performConcurrentWorkOnRoot (omitted/node_modules/react-dom/cjs/react-dom.development.js:25809:7)
        at flushActQueue (omitted/node_modules/react/cjs/react.development.js:2667:24)
        at recursivelyFlushAsyncActWork (omitted/node_modules/react/cjs/react.development.js:2633:9)
        at omitted/node_modules/react/cjs/react.development.js:2545:15 {
      detail: SyntaxError: \8 and \9 are not allowed in strict mode.
          at Function (<anonymous>)
          at compile (omitted/node_modules/nwsapi/src/nwsapi.js:760:17)
          at match_collect (omitted/node_modules/nwsapi/src/nwsapi.js:1339:16)
          at Object._matches [as match] (omitted/node_modules/nwsapi/src/nwsapi.js:1394:35)
          at exports.matchesDontThrow (omitted/node_modules/jsdom/lib/jsdom/living/helpers/selectors.js:29:36)
          at matches (omitted/node_modules/jsdom/lib/jsdom/living/helpers/style-rules.js:50:10)
          at omitted/node_modules/jsdom/lib/jsdom/living/helpers/style-rules.js:35:18
          at Array.forEach (<anonymous>)
          at handleSheet (omitted/node_modules/jsdom/lib/jsdom/living/helpers/style-rules.js:26:13)
          at Array.forEach (<anonymous>)
          at exports.forEachMatchingSheetRuleOfElement (omitted/node_modules/jsdom/lib/jsdom/living/helpers/style-rules.js:46:11)
          at getComputedStyle (omitted/node_modules/jsdom/lib/jsdom/browser/Window.js:806:5)
          at getContentBoxWidth (omitted/node_modules/src/top-navigation/use-top-navigation.ts:166:17)
          at recalculateFit (omitted/node_modules/src/top-navigation/use-top-navigation.ts:82:28)
          at omitted/node_modules/src/top-navigation/use-top-navigation.ts:124:7
          at commitAttachRef (omitted/node_modules/react-dom/cjs/react-dom.development.js:23650:18)
          at commitLayoutEffectOnFiber (omitted/node_modules/react-dom/cjs/react-dom.development.js:23503:9)
          at commitLayoutMountEffects_complete (omitted/node_modules/react-dom/cjs/react-dom.development.js:24688:9)
          at commitLayoutEffects_begin (omitted/node_modules/react-dom/cjs/react-dom.development.js:24674:7)
          at commitLayoutEffects (omitted/node_modules/react-dom/cjs/react-dom.development.js:24612:3)
          at commitRootImpl (omitted/node_modules/react-dom/cjs/react-dom.development.js:26823:5)
          at commitRoot (omitted/node_modules/react-dom/cjs/react-dom.development.js:26682:5)
          at performSyncWorkOnRoot (omitted/node_modules/react-dom/cjs/react-dom.development.js:26117:3)
          at flushSyncCallbacks (omitted/node_modules/react-dom/cjs/react-dom.development.js:12042:22)
          at commitRootImpl (omitted/node_modules/react-dom/cjs/react-dom.development.js:26959:3)
          at commitRoot (omitted/node_modules/react-dom/cjs/react-dom.development.js:26682:5)
          at finishConcurrentRender (omitted/node_modules/react-dom/cjs/react-dom.development.js:25981:9)
          at performConcurrentWorkOnRoot (omitted/node_modules/react-dom/cjs/react-dom.development.js:25809:7)
          at flushActQueue (omitted/node_modules/react/cjs/react.development.js:2667:24)
          at recursivelyFlushAsyncActWork (omitted/node_modules/react/cjs/react.development.js:2633:9)
          at omitted/node_modules/react/cjs/react.development.js:2545:15,
      type: 'unhandled exception'
    }

      at VirtualConsole.<anonymous> (node_modules/jest-environment-jsdom/build/index.js:63:23)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:4213:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4277:31)
      at reportUncaughtErrorInDEV (node_modules/react-dom/cjs/react-dom.development.js:22838:5)
      at captureCommitPhaseError (node_modules/react-dom/cjs/react-dom.development.js:27126:5)
      at commitLayoutMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24690:9)
      at commitLayoutEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24674:7)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:24612:3)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26823:5)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26117:3)
      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26959:3)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at finishConcurrentRender (node_modules/react-dom/cjs/react-dom.development.js:25981:9)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25809:7)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at recursivelyFlushAsyncActWork (node_modules/react/cjs/react.development.js:2633:9)
      at node_modules/react/cjs/react.development.js:2545:15

  console.error
    The above error occurred in the <div> component:
    
        at div
        at Portal (omitted/node_modules/src/internal/components/portal/index.tsx:48:34)
        at div
        at VisualContext (omitted/node_modules/src/internal/components/visual-context/index.tsx:38:41)
        at div
        at InternalTopNavigation (omitted/node_modules/src/top-navigation/internal.tsx:27:3)
        at TopNavigation (omitted/node_modules/src/top-navigation/index.tsx:12:41)
        at div
        at AppHeader (omitted/src/components/custom/AppHeader/content.tsx:159:48)
        at AuthProvider (omitted/src/components/builtin/auth/index.tsx:87:61)
        at Router (omitted/node_modules/react-router/lib/components.tsx:413:13)
        at BrowserRouter (omitted/node_modules/react-router-dom/index.tsx:757:3)
        at App (omitted/src/App.tsx:28:37)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-dom/cjs/react-dom.development.js:18687:23)
      at update.callback (node_modules/react-dom/cjs/react-dom.development.js:18720:5)
      at callCallback (node_modules/react-dom/cjs/react-dom.development.js:13923:12)
      at commitUpdateQueue (node_modules/react-dom/cjs/react-dom.development.js:13944:9)
      at commitLayoutEffectOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23391:13)
      at commitLayoutMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24688:9)
      at commitLayoutEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24674:7)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:24612:3)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26823:5)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26117:3)
      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26959:3)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at finishConcurrentRender (node_modules/react-dom/cjs/react-dom.development.js:25981:9)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25809:7)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at recursivelyFlushAsyncActWork (node_modules/react/cjs/react.development.js:2633:9)
      at node_modules/react/cjs/react.development.js:2545:15

 FAIL  src/App.test.tsx
  App
    ✕ renders app (591 ms)

  ● App › renders app

    SyntaxError: \8 and \9 are not allowed in strict mode.
        at Function (<anonymous>)

      at compile (node_modules/nwsapi/src/nwsapi.js:760:17)
      at match_collect (node_modules/nwsapi/src/nwsapi.js:1339:16)
      at Object._matches [as match] (node_modules/nwsapi/src/nwsapi.js:1394:35)
      at exports.matchesDontThrow (node_modules/jsdom/lib/jsdom/living/helpers/selectors.js:29:36)
      at matches (node_modules/jsdom/lib/jsdom/living/helpers/style-rules.js:50:10)
      at node_modules/jsdom/lib/jsdom/living/helpers/style-rules.js:35:18
          at Array.forEach (<anonymous>)
      at handleSheet (node_modules/jsdom/lib/jsdom/living/helpers/style-rules.js:26:13)
          at Array.forEach (<anonymous>)
      at exports.forEachMatchingSheetRuleOfElement (node_modules/jsdom/lib/jsdom/living/helpers/style-rules.js:46:11)
      at getComputedStyle (node_modules/jsdom/lib/jsdom/browser/Window.js:806:5)
      at getContentBoxWidth (node_modules/src/top-navigation/use-top-navigation.ts:166:17)
      at recalculateFit (node_modules/src/top-navigation/use-top-navigation.ts:82:28)
      at node_modules/src/top-navigation/use-top-navigation.ts:124:7
      at commitAttachRef (node_modules/react-dom/cjs/react-dom.development.js:23650:18)
      at commitLayoutEffectOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23503:9)
      at commitLayoutMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24688:9)
      at commitLayoutEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24674:7)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:24612:3)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26823:5)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26117:3)
      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26959:3)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at finishConcurrentRender (node_modules/react-dom/cjs/react-dom.development.js:25981:9)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25809:7)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at recursivelyFlushAsyncActWork (node_modules/react/cjs/react.development.js:2633:9)
      at node_modules/react/cjs/react.development.js:2545:15

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.244 s
Ran all test suites.
```

### Source code

Upon checking the code, it might be related to the CSS. Here is the example.

```
node_modules/@cloudscape-design/components/table/body-cell/styles.scoped.css:.awsui_body-cell_c6tup_1ls9v_107:not(#\9):first-child:not(.awsui_is-visual-refresh_c6tup_1ls9v_136) {
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by just-boris** [comment]
Very likely you are facing this issue: https://github.com/dperini/nwsapi/issues/92

It is nothing we can fix on our end, but PR contributions to the upstream may unblock you

**Comment by flymauntains** [comment]
It is important that if file router includes number such as `F:\solana\814\generate-keypair.ts.` If it is true, file router must set without number.
