### ISSUE TITLE
[Bug]: ReferenceError: window is not defined | Out Of AppLayout

### ISSUE THREAD

**Issue by MwSpaceLLC** [cloudscape-design/components#2804]
### Browser

Chrome, Safari, Firefox, Edge

### Package version

^3.0.775

### React version

^18.3.1

### Description

Plain **client component** mound with PieChart on nextjs without App layout

### Source code

```
'use client'

import * as React from "react";

import PieChart from "@cloudscape-design/components/pie-chart";

import {Container} from "@cloudscape-design/components";

export default function PageCharts({data}) {

    const data02 = data.map(d => ({title: d.name, value: d.total}))

    return (
        <section className="py-6">
            <Container>
                <PieChart
                    hideFilter
                    variant="donut"
                    data={[data02[0]]}
                    detailPopoverContent={(datum, sum) => [
                        {key: "Resource count", value: datum.value},
                        {
                            key: "Percentage",
                            value: `${((datum.value / sum) * 100).toFixed(
                                0
                            )}%`
                        },
                        {key: "Last update on", value: datum.lastUpdate}
                    ]}
                    segmentDescription={(datum, sum) =>
                        `${datum.value} units, ${(
                            (datum.value / sum) *
                            100
                        ).toFixed(0)}%`
                    }
                />
            </Container>
        </section>
    )

}
```

### Reproduction

Create component client Out Of AppLayout

errors:

```batch
 GET / 500 in 9363ms
 ⨯ ..\src\internal\utils\dom.ts (37:3) @ parseCssVariable
 ⨯ Internal error: ReferenceError: window is not defined
    at parseCssVariable (./node_modules/@cloudscape-design/components/internal/utils/dom.js:42:5)
    at createCategoryColorScale (./node_modules/@cloudscape-design/components/internal/utils/create-category-color-scale.js:19:75)
    at eval (./node_modules/@cloudscape-design/components/pie-chart/index.js:86:111)
    at Object.oN [as useMemo] (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:12:68806)
    at t.useMemo (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:162732)
    at PieChart (./node_modules/@cloudscape-design/components/pie-chart/index.js:85:64)
    at au (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:10446)
    at W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:15122
    at aw (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:16908)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:49776)
    at aj (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:53793)
    at W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:42336
    at aw (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:42822)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:49776)
    at aj (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:53793)
    at aC (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:52874)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:50095)
    at aj (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:53793)
    at W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:42336
    at aw (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:42822)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:49776)
    at aj (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:53793)
    at aC (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:52874)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:50095)
    at aj (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:53793)
    at W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:42336
    at aw (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:42822)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:49776)
    at aj (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:53793)
    at ab (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:11759)
    at W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:16871
    at aw (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:16908)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:49776)
    at ab (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:11808)
    at W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:16871
    at aw (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:16908)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:49776)
    at aw (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:45321)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:49776)
    at aj (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:53793)
    at ab (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:11759)
    at W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:16871
    at aw (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:16908)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:49776)
    at ab (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:11808)
    at W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:16871
    at aw (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:16908)
    at a_ (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:49776)
    at aj (W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:53793)
    at W:\clienti\admin.mateg.it\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:42336
digest: "599897103"
  35 |  */
  36 | export function parseCssVariable(value: string) {
> 37 |   if (window.CSS?.supports?.('color', 'var(--dummy, #000)') ?? false) {
     |   ^
  38 |     return value;
  39 |   }
  40 |
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by hausdora** [comment]
Same with Linechart

```
[1] ReferenceError: window is not defined
[1]     at parseCssVariable (webpack-internal:///./node_modules/@cloudscape-design/components/internal/utils/dom.js:54:5)
[1]     at createCategoryColorScale (webpack-internal:///./node_modules/@cloudscape-
...............
[1]  ⨯ ReferenceError: window is not defined
[1]     at parseCssVariable (webpack-internal:///./node_modules/@cloudscape-design/components/internal/utils/dom.js:54:5)
[1]     at createCategoryColorScale (webpack-internal:///./node_modules/@cloudscape-design/components/internal/utils/create-category-color-scale.js:19:75)
[1]     at eval (webpack-internal:///./node_modules/@cloudscape-design/components/mixed-line-bar-chart/internal.js:117:111)
[1]     at Object.useMemo (src/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5124:19)
[1]     at useMemo (/portal/src/node_modules/react/cjs/react.development.js:1650:21)
[1]     at InternalMixedLineBarChart (webpack-internal:///./node_modules/@cloudscape-design/components/mixed-line-bar-chart/internal.js:114:66)
[
[1]   46 |  */
[1]   47 | export function parseCssVariable(value: string) {
[1] > 48 |   if (window.CSS?.supports?.('color', 'var(--dummy, #000)') ?? false) {
[1]      |   ^
[1]   49 |     return value;
[1]   50 |   }
[1]   51 |
```

**Comment by pan-kot** [comment]
Hello,

Thanks for reporting the bug!

I merged the fix and it should be available in the npm package soon.
