### ISSUE TITLE
[Bug]: SpaceBetween and Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by krzysztof-miemiec** [cloudscape-design/components#451]
### Browser

Chrome

### Package version

v3.0.108

### React version

17.0.2

### Description

I know that `SpaceBetween` component can not be used with non-element children, per documentation:
> This component only supports element children (components or HTML elements). Primitive values will cause [React's missing key warning. ](https://reactjs.org/docs/lists-and-keys.html#keys) If you want to put a string or a number as a direct child, wrap it into a <span>.

However, expressions that evaluate to `false` are not shown by React in any way, yet they result in the following error:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `InternalSpaceBetween`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at InternalSpaceBetween (https://8z2crx.csb.app/node_modules/@cloudscape-design/components/space-between/internal.js:16:15)
    at SpaceBetween (https://8z2crx.csb.app/node_modules/@cloudscape-design/components/space-between/index.js:14:15)
    at App (https://8z2crx.csb.app/src/App.js:28:41)
```

To avoid this issue, one has to change expression such as:
```jsx
{showSomeAlert && (
  <Alert>
    Some message.
  </Alert>
)}
```

into:
```jsx
{showSomeAlert ? (
  <Alert>
    Some message.
  </Alert>
): null}
```

which is slightly less concise. Could SpaceBetween component filter out falsey children to avoid this issue?

### Source code

See CodeSandbox below.

### Reproduction

1. Go to https://codesandbox.io/s/vigilant-lake-8z2crx?file=/src/App.js
2. Remove character from the input and see missing key warning.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by pan-kot** [comment]
Hello Krzysztof,

Thanks for reporting your finding!

I am afraid that filtering out the falsy values might be dangerous at this point because there can be customers relying on that. It might be less relevant for an empty string but definitely can happen for a number 0. However, I will discuss with the team if we can reflect this case on our website.

Btw, there is one more way to avoid the issue - you can ensure the left-hand side of the && expression is a boolean:
```
{!!showSomeAlert && (
  <Alert>
    Some message.
  </Alert>
)}
```

**Comment by just-boris** [comment]
Closing due to inactivity. Feel free to reopen if there are still some open questions
