### ISSUE TITLE
[Bug]: Multiselect filtering throws error if value in option is an Object and not a string

### ISSUE THREAD

**Issue by athermantis** [cloudscape-design/components#504]
### Package version

v3.0.126

### React version

v18.2.0

### Description

If you have an object as the value of the target, attempting to enter any text into the filter will result in a js error and react crash. JS error in console:

`Uncaught TypeError: value.toLowerCase is not a function
    at matchesString (filter-options.ts:12:1)
    at searchStrFields (filter-options.ts:22:1)
    at Array.some (<anonymous>)
    at matchesSingleOption (filter-options.ts:28:1)
    at filter-options.ts:60:1
    at Array.reduce (<anonymous>)
    at filterOptions (filter-options.ts:44:1)
    at prepareOptions (prepare-options.ts:13:1)
    at internal.tsx:88:1
    at renderWithHooks (react-dom.development.js:16303:1)`

Documentation states that filter will try to match on substring values in label and value (https://cloudscape.design/components/multiselect/?tabId=api). Maybe we can skip searching the value if it is an object?

Not sure if this should be a feature request or bug report.

### Reproduction

import * as React from "react";
import Multiselect from "@cloudscape-design/components/multiselect";

export default () => {
  const [
    selectedOptions,
    setSelectedOptions
  ] = React.useState([
    {
      label: "Option 1",
      value: { id: "mine" },
      description: "This is a description"
    }
  ]);
  return (
    <Multiselect
      selectedOptions={selectedOptions}
      onChange={({ detail }) =>
        setSelectedOptions(detail.selectedOptions)
      }
      options={[
        {
          label: "Group 1",
          options: [
            {
              label: "Option 1",
              value: { id: "mine" },
              description: "This is a description"
            },
            {
              label: "Option 2",
              value: "2",
              iconName: "unlocked",
              labelTag: "This is a label tag"
            }
          ]
        },
        {
          label: "Group 2",
          options: [
            {
              label: "Option 3 (disabled)",
              value: "3",
              iconName: "share",
              tags: ["Tags go here", "Tag1", "Tag2"],
              disabled: true
            },
            {
              label: "Option 4",
              value: "4",
              filteringTags: [
                "filtering",
                "tags",
                "these are filtering tags"
              ]
            }
          ]
        },
        {
          label: "Group 3 (disabled)",
          disabled: true,
          options: [
            { label: "Option 5", value: "5" },
            { label: "Option 6", value: "6" }
          ]
        }
      ]}
      filteringType="auto"
      placeholder="Choose options"
      selectedAriaLabel="Selected"
    />
  );
}

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by just-boris** [comment]
Hello!

The same documentation page you linked also states that label type should be a string. Same in our typescript definitions.

Rendering a non-string component is not supported. If you give more details about your use-case, I may try recommending an alternative

**Comment by athermantis** [comment]
Thanks @just-boris, sorry I missed that. 

In a grouped multi-select scenario, I'm trying to tie the main item and sub items together in a rational way. Use case- if an option corresponds to a date, I want to render sub options of year, month, week, day underneath it, but simply using the value of "month" will lose the connection to the top level option, hence trying to use the object to do this programmatically.

**Comment by just-boris** [comment]
There is a built-in group rendering feature: https://cloudscape.design/components/select/?tabId=playground&example=with-groups

Rendering custom options UI is not supported

**Comment by just-boris** [comment]
Closing due to inactivity. Feel free to reopen if you have additional questions
