### ISSUE TITLE
[Bug]: Can't use wrapper from test-utils, it fails to import with obfuscated stack trace

### ISSUE THREAD

**Issue by spence95** [cloudscape-design/components#778]
### Browser

Chrome, Safari, Firefox, Edge

### Package version

3.0.201

### React version

18.2.0

### Description

When running unit tests and using `import wrapper from "@cloudscape-design/components/test-utils/dom"`

I get the error at the import line:

```
/node_modules/@cloudscape-design/components/test-utils/dom/index.js: Cannot read properties of undefined (reading '0')
```

Full error here:

```
FAIL tests/src/components/dropdown.test.tsx
 ● Test suite failed to run

 TypeError: /node_modules/@cloudscape-design/components/test-utils/dom/index.js: Cannot read properties of undefined (reading '0')

   2 | import { render } from "@testing-library/react";
   3 | import Dropdown from "../../../src/components/dropdown";
 > 4 | import wrapper from "@cloudscape-design/components/test-utils/dom";
     | ^
   5 | import "@testing-library/jest-dom";
   6 | import { act } from "react-dom/test-utils";
   7 |

   at new SourceMap (node_modules/@babel/generator/src/source-map.ts:61:42)
   at new Generator (node_modules/@babel/generator/src/index.ts:24:35)
   at generate (node_modules/@babel/generator/src/index.ts:271:15)
   at generateCode (node_modules/@babel/core/src/transformation/file/generate.ts:35:22)
   at run (node_modules/@babel/core/src/transformation/index.ts:59:48)
       at run.next (<anonymous>)
   at transform (node_modules/@babel/core/src/transform.ts:29:20)
       at transform.next (<anonymous>)
   at evaluateSync (node_modules/gensync/index.js:251:28)
   at sync (node_modules/gensync/index.js:89:14)
   at fn (node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:97:14)
   at transformSync (node_modules/@babel/core/src/transform.ts:66:52)
   at Object.<anonymous> (tests/src/components/dropdown.test.tsx:4:1)
```
This is with Node v16.9.0

### Source code

I can't link the full source code but this is the unit test:

```
import React from "react";
import { render } from "@testing-library/react";
import Dropdown from "../../../src/components/dropdown";
import wrapper from "@cloudscape-design/components/test-utils/dom";
import "@testing-library/jest-dom";
import { act } from "react-dom/test-utils";

jest.mock("../../../src/components/shared", () => ({
    populateItemTable: () => Promise.resolve(),
    populateInventoryPlanTable: () => Promise.resolve(),
    populateUpDownStreamTable: () => Promise.resolve(),
    populateTransferPlanTable: () => Promise.resolve()
}));

describe("Dropdown component", () => {
    const options = [
        { label: "Option 1", value: "C1" },
        { label: "Option 2", value: "C2" },
        { label: "Option 3", value: "C3" }
    ];
    const onChange = jest.fn();

    test("displays the options", () => {
        const { container, getByText } = render(
            <Dropdown options={options} dropdownType="Location" onChange={onChange} />
        );

        // find a select trigger in your application using test utils
        const trigger = wrapper(container).findSelect();

        // open the select by clicking on the trigger
        act(() => {
            trigger?.openDropdown();
        });
        options.forEach(option => {
            expect(getByText(option.label)).toBeInTheDocument();
        });
    });

    test("calls the appropriate setters when an option is selected", async () => {
        const { container, getByLabelText } = render(
            <Dropdown options={options} dropdownType="Location" onChange={onChange} />
        );

        // open the select by clicking on the trigger
        const trigger = wrapper(container).findSelect();
        trigger?.openDropdown();
        act(() => {
            trigger?.selectOption(2);
        });

        expect(onChange).toHaveBeenCalledWith(options[1].value);
    });

    test("passed in selector methods are called appropriately", async () => {
        const setSelectedOptionMock = jest.fn();
        const { container, getByLabelText } = render(
            <Dropdown
                options={options}
                dropdownType="Location"
                onChange={onChange}
                selectedOption={options[0]}
                setSelectedOption={setSelectedOptionMock}
            />
        );

        // open the select by clicking on the trigger
        const trigger = wrapper(container).findSelect();
        trigger?.openDropdown();
        act(() => {
            trigger?.selectOption(2);
        });
        expect(setSelectedOptionMock).toHaveBeenCalledWith(options[1]);
        expect(onChange).toHaveBeenCalledWith(options[1].value);
    });
});
```

And this is the package.json:

```
{
    "name": "website",
    "version": "1.0.0",
    "private": true,
    "dependencies": {
        "@aws-amplify/core": "^5.0.7",
        "@aws-amplify/storage": "^5.0.7",
        "@aws-amplify/ui-react": "^4.1.0",
        "@cloudscape-design/components": "^3.0.201",
        "@cloudscape-design/global-styles": "^1.0.7",
        "@emotion/react": "^11.10.5",
        "@emotion/styled": "^11.10.5",
        "@mui/icons-material": "^5.11.0",
        "@mui/material": "^5.11.0",
        "@mui/x-date-pickers": "^5.0.13",
        "@testing-library/jest-dom": "^5.16.5",
        "@testing-library/react": "^13.4.0",
        "@testing-library/user-event": "^13.5.0",
        "@types/jest": "^27.5.2",
        "@types/node": "^16.18.4",
        "@types/react": "^18.0.25",
        "@types/react-dom": "^18.0.9",
        "aws-amplify": "^5.0.4",
        "bootstrap": "^5.2.3",
        "identity-obj-proxy": "^3.0.0",
        "jest-environment-jsdom": "^29.3.1",
        "material-react-table": "^1.4.3",
        "neptune": "file:../shared/neptune",
        "react": "^18.2.0",
        "react-bootstrap": "^2.7.0",
        "react-dom": "^18.2.0",
        "react-router-dom": "^6.5.0",
        "react-scripts": "^5.0.1",
        "react-toastify": "^9.1.1",
        "reactflow": "^11.4.0",
        "ts-jest": "^29.0.3",
        "ts-node": "^10.9.1",
        "typescript": "^4.9.3",
        "util": "file:../shared/util",
        "web-vitals": "^3.1.1"
    },
    "devDependencies": {
        "@cloudscape-design/jest-preset": "^2.0.8",
        "@cloudscape-design/test-utils-core": "^1.0.9",
        "@jest/globals": "^29.4.2",
        "@testing-library/jest-dom": "^5.16.5",
        "@types/jest": "^29.2.1",
        "@types/testing-library__jest-dom": "^5.14.5",
        "@typescript-eslint/eslint-plugin": "^5.42.0",
        "@typescript-eslint/parser": "^5.42.0",
        "eslint": "^8.26.0",
        "eslint-config-prettier": "^8.5.0",
        "eslint-config-standard-with-typescript": "^23.0.0",
        "eslint-plugin-header": "^3.1.1",
        "eslint-plugin-import": "^2.26.0",
        "eslint-plugin-jsdoc": "^39.6.4",
        "eslint-plugin-n": "^15.4.0",
        "eslint-plugin-node": "^11.1.0",
        "eslint-plugin-prettier": "^4.2.1",
        "eslint-plugin-promise": "^6.1.1",
        "jest": "^29.2.2",
        "prettier": "^2.7.1",
        "ts-jest": "^29.0.3",
        "ts-node": "^10.9.1",
        "typescript": "^4.8.4"
    },
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "jest --coverage",
        "eject": "react-scripts eject",
        "prettier": "prettier --write ."
    },
    "eslintConfig": {
        "extends": [
            "react-app",
            "react-app/jest"
        ]
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "jest": {
        "transform": {
            "^.+\\.tsx?$": "ts-jest"
        },
        "testMatch": [
            "**/*.test.tsx",
            "**/*.test.ts"
        ],
        "moduleFileExtensions": [
            "ts",
            "tsx",
            "js",
            "jsx",
            "json"
        ],
        "resolver": "<rootDir>/src/resolver.js",
        "moduleNameMapper": {
            "\\.(css|scss)$": "identity-obj-proxy"
        },
        "preset": "@cloudscape-design/jest-preset",
        "testEnvironment": "jsdom",
        "setupFilesAfterEnv": [
            "<rootDir>/src/setupTests.ts"
        ]
    }
}
```

### Reproduction

If you take that package.json and the unit test but substitute something else for the component, you will get the same error.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by Al-Dani** [comment]
Hey @spence95
Thanks a lot for reaching out!

This might probably be an issue with the setup. I see that you are using cloudscape `jest-preset`. Your own `transform`  settings might be in conflict with the one coming from the preset. Could you try to remove the following:

`"transform": {
            "^.+\\.tsx?$": "ts-jest"
        },`
